### ISSUE TITLE
Hamburger menu on (mobile) player view, squashes the UI

### ISSUE THREAD

**Issue by TomRHandcock** [TomRHandcock/ECM2434-GSEP#1]
When opening the hamburger menu on the mobile player view the main UI is squashed vertically, use some Z-index and margin to sort it out, bit fiddly.

**Comment by TomRHandcock** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Hamburger menu on (mobile) player view, squashes the UI](https://trello.com/c/CLFF3Msf/72-hamburger-menu-on-mobile-player-view-squashes-the-ui)

**Comment by AlexWesterman** [comment]
Fixed in the next mater branch commit.
