### ISSUE TITLE
Scores in the gamemaster overview screen can overflow onto a new line

### ISSUE THREAD

**Issue by owen-saunders** [TomRHandcock/ECM2434-GSEP#10]
Need to ensure that scores cannot be multiline.

![image](https://user-images.githubusercontent.com/56914238/75976409-4a3ee380-5ed2-11ea-8846-c04e125b9dff.png)

**Comment by TomRHandcock** [comment]
Fixed this issue, there is nothing on Trello for it so I'll just mark it as done here.
