### ISSUE TITLE
First question for player won't appear if you click 'Answer Questions' before the database loads

### ISSUE THREAD

**Issue by owen-saunders** [TomRHandcock/ECM2434-GSEP#11]
If you do not wait for the description of the location to load in the player view, then when you click answer questions you do not get the first question appearing, only the next question button which takes you to the second question.

**Comment by galexite** [comment]
This shouldn’t be a problem if the ‘Answer Questions’ button appears only after scanning and verifying a QR code.

**Comment by owen-saunders** [comment]
Ah I see it wouldn't be a problem. I was expecting that the database would retrieve the description after a QR code has been scanned, but if it's done before the QR Code is scanned, then the problem won't occur, unless you can click into the QR code, scan and return before the database loads, which is nigh impossible. Closed since not bug in production.
