### ISSUE TITLE
Two extra locations appear in 'Questions' view

### ISSUE THREAD

**Issue by TomRHandcock** [TomRHandcock/ECM2434-GSEP#13]

**Comment by TomRHandcock** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Two extra locations appear in 'Questions' view](https://trello.com/c/ip9RTFNY/112-two-extra-locations-appear-in-questions-view)

**Comment by AlexWesterman** [comment]
Fixed in latest commit
