### ISSUE TITLE
User is unable to add a new question to a location that doesn't have any questions yet

### ISSUE THREAD

**Issue by TomRHandcock** [TomRHandcock/ECM2434-GSEP#14]

**Comment by TomRHandcock** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [User is unable to add a new question to a location that doesn't have any questions yet](https://trello.com/c/V5GwCmpd/113-user-is-unable-to-add-a-new-question-to-a-location-that-doesnt-have-any-questions-yet)

**Comment by AlexWesterman** [comment]
Fix in latest commit
