### ISSUE TITLE
Buttons are hard to see against similar blue background

### ISSUE THREAD

**Issue by galexite** [TomRHandcock/ECM2434-GSEP#18]
It's quite hard to see buttons in the `player-main` component against the similarly blue background.

**Comment by galexite** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Buttons are hard to see against blue background](https://trello.com/c/S4tMs8wv/118-buttons-are-hard-to-see-against-blue-background)

**Comment by AlexWesterman** [comment]
Adjusted the colours of the button and background slightly as well as added white board to all buttons. See latest commit
