### ISSUE TITLE
Team ID undefined when joining team

### ISSUE THREAD

**Issue by owen-saunders** [TomRHandcock/ECM2434-GSEP#19]
An old implementation of the team id selection using alert boxes is causing undefined errors, and assigning users to team 0 every time. 
This implementation needs to be moved to the new system with the styled screen. This error has probably occurred due to the major refactoring.

**Comment by owen-saunders** [comment]
Trello Link
[https://trello.com/c/k9Ep7pRI/121-team-id-undefined-when-joining-team](url)

**Comment by TomRHandcock** [comment]
Fixed this issue.
