### ISSUE TITLE
Assigning mapbox.accessToken causes error because variable is read only.

### ISSUE THREAD

**Issue by TomRHandcock** [TomRHandcock/ECM2434-GSEP#2]

**Comment by TomRHandcock** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Assigning mapbox.accessToken causes error because variable is read only](https://trello.com/c/k8Sef1Go/80-assigning-mapboxaccesstoken-causes-error-because-variable-is-read-only)

**Comment by owen-saunders** [comment]
Need to use 'accessToken' not mapbox.accessToken and make sure it is assigned in mapboxgl.Map({container....., accessToken: 'token', style:....}) constructor instead of assigning to the Read-Only attributes of mapboxgl.
