### ISSUE TITLE
Gamemaster is unable to update the database with local changes to locations.

### ISSUE THREAD

**Issue by TomRHandcock** [TomRHandcock/ECM2434-GSEP#20]

**Comment by TomRHandcock** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Gamemaster not able to delete or edit locations](https://trello.com/c/BpHUq13T/126-gamemaster-not-able-to-delete-or-edit-locations)

**Comment by TomRHandcock** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Location screen doesn't add location properly](https://trello.com/c/lFb7GTYc/122-location-screen-doesnt-add-location-properly)

**Comment by AlexWesterman** [comment]
Fixed in latest commit
