### ISSUE TITLE
Attempting to answer questions multiple times will cause the app to redirect the player to the main player screen.

### ISSUE THREAD

**Issue by TomRHandcock** [TomRHandcock/ECM2434-GSEP#7]

**Comment by TomRHandcock** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Attempting to answer questions multiple times will cause the app to redirect the player to the main player screen](https://trello.com/c/5d25O9eK/91-attempting-to-answer-questions-multiple-times-will-cause-the-app-to-redirect-the-player-to-the-main-player-screen)

**Comment by AlexWesterman** [comment]
Fixed in next commit (not yet committed)
