### ISSUE TITLE
Width of player view containers change based on text content

### ISSUE THREAD

**Issue by AlexWesterman** [TomRHandcock/ECM2434-GSEP#9]
See https://trello.com/c/QuRCSU5J/94-width-of-player-view-containers-change-based-on-text-content

**Comment by owen-saunders** [comment]
[https://github.com/TomRHandcock/ECM2434-GSEP/commit/cfda56f503fdab1b80957cde4c0be1f0d06674c9](url)

Closed by fixing the size of the surrounding container for player question text.
